on:
  push:
    branches:
      - main

jobs:
  create-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Check for marker file
        id: check_marker
        run: |
          if [ -f .github/issues_created ]; then
            echo "should_create=false" >> $GITHUB_OUTPUT
          else
            echo "should_create=true" >> $GITHUB_OUTPUT
          fi

      - name: Create marker file
        if: steps.check_marker.outputs.should_create == 'true'
        run: echo "Issues created on $(date)" > .github/issues_created

      - name: Commit marker file
        if: steps.check_marker.outputs.should_create == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/issues_created
          git commit -m "Mark issues as created" || exit 0
          git push

      - name: Create the purpose and scope issue
        if: steps.check_marker.outputs.should_create == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/purpose_and_scope_issue.md

      - name: Create the priorities issue
        if: steps.check_marker.outputs.should_create == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/priorities_issue.md

      - name: Create the iterate and refactor issue
        if: steps.check_marker.outputs.should_create == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/iterate_and_refactor_issue.md

      - name: Create the communicate and validate issue
        if: steps.check_marker.outputs.should_create == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/communicate_and_validate_issue.md

      - name: Create the maintain discipline issue
        if: steps.check_marker.outputs.should_create == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/maintain_discipline_issue.md
