on:
  push:
    branches:
      - main

jobs:
  create-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Check if first commit
        id: first_commit
        run: |
          if [ "$(git rev-list --count HEAD)" -eq 1 ]; then
            echo "first_commit=true" >> $GITHUB_OUTPUT
          else
            echo "first_commit=false" >> $GITHUB_OUTPUT
          fi

      - name: Create the purpose and scope issue
        if: steps.first_commit.outputs.first_commit == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/purpose_and_scope_issue.md

      - name: Create the priorities issue
        if: steps.first_commit.outputs.first_commit == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/priorities_issue.md

      - name: Create the iterate and refactor issue
        if: steps.first_commit.outputs.first_commit == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/iterate_and_refactor_issue.md

      - name: Create the communicate and validate issue
        if: steps.first_commit.outputs.first_commit == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/communicate_and_validate_issue.md

      - name: Create the maintain discipline issue
        if: steps.first_commit.outputs.first_commit == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/maintain_discipline_issue.md
